### ISSUE TITLE
Email retains "is-error" styling even after valid email is entered 

### ISSUE THREAD

**Issue by kedskeds** [hankchizljaw/boilerform#14]
## Steps to Reproduce the Problem

1. Go to this CodePen: https://codepen.io/hankchizljaw/pen/dZLydK?editors=1001
2. Attempt a submission with none of the fields filled out.
3. Notice that "Name" and "Email" have red borders.
4. Enter a valid Email address, while still keeping Name blank.
5. Click Submit and notice that Email still has a red border even though the input is valid.

**Comment by Andy-set-studio** [comment]
Good catch, @kedskeds. Thank you!

**Comment by Andy-set-studio** [comment]
This could be related to #5 possibly.

**Comment by labsvisual** [comment]
Can I grab this one?

**Comment by Andy-set-studio** [comment]
Of course, thank you so much. I’ll assign you now🙂

**Comment by Andy-set-studio** [comment]
It won’t let me assign you for some reason, but it’s yours!

**Comment by labsvisual** [comment]
Oh, no worries! Try using my username `labsvisual`. However, I have started it! 😄

**Comment by Andy-set-studio** [comment]
Ah cool! Yeh it won't let me add you to the list, even when I use your username 😔

Oh well, thanks for getting started! 🚀

**Comment by Andy-set-studio** [comment]
Fixed with PR #15
