### ISSUE TITLE
Focus management is janky if `setCustomValidity` is used

### ISSUE THREAD

**Issue by Andy-set-studio** [hankchizljaw/boilerform#5]
If a custom validation message is set, using the `data-validation-message` attribute, the Validation Interface needs to check it manually as it never natively declares itself as valid. The problem is that it focuses when the user tries to submit the form. 

### Evironment
<details>
    <summary>Support details data dump</summary>
Operating System: Mac OSX 10 (Unknown Version)<br />
Web Browser: Chrome 63.0.3239.108<br />
Screen Resolution: 1440 x 900<br />
Browser Size: 1440 x 755<br />
Javascript: Yes<br />
Cookies: Yes<br />
Color Depth: 24<br />

User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X
10_13_2) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/63.0.3239.108 Safari/537.36
</details>

### To recreate 
- Add a custom validation message to an element with `data-validation-message`
- Attempt to submit the form
- See the custom validation message
- Fill that field to make sure it will be valid 
- Attempt to submit
- See that the field is focused

### Screencast
![A screencast of the bug in question](https://media.giphy.com/media/l49JLu5xTlR7MDYTm/giphy.gif)

**Comment by gnclmorais** [comment]
What would be the expected behaviour, @hankchizljaw?

**Comment by Andy-set-studio** [comment]
I would expect that because the name field is valid, the focus should be on the invalid email field. I suspect that the name is maybe still registering as invalid at the point on focus? 

It’s a tough one!

**Comment by Andy-set-studio** [comment]
Fixed with PR #15
